### ISSUE TITLE
Improve generated helpers size

### ISSUE THREAD

**Issue by marvinhagemeister** [rpetrich/babel-plugin-transform-async-to-promises#18]
Since I can't sleep anyway I spent the last half hour comparing the generated code to the one generated by `nodent`. What's cool is that this plugin fixes one bug where `nodent` didn't manage to catch an error properly 🎉👍

1) Remove support for environments which don't support at least `ES 5.1`
2) Simplify `_async`. Ideally it could be something shorter with less closures like this:

```js
function _async(fn) {
  return function() {
    try {
      return Promise.resolve(fn.apply(this, arguments));
    } catch(e) {
      return Promise.reject(e);
    }
  }
}

const foo = _async(function(...args) {
  // ...
});
```

2) Inline `_await` resolution logic.

`_await` could be inlined with a bit of overhead inside the babel plugin. This would make the plugin code likely a bit more complex because a 1:1 translation is not as easy anymore and one would need to keep track of the created `Promises`.

```js
// current
_await(foo(...args), function(_foo) {
  // ...
});

// suggested
Promise.resolve(foo(...args)).then(function(_foo) {
  // ...
});
```

Relevant thread: https://github.com/developit/microbundle/pull/252#issuecomment-441405335

**Comment by rpetrich** [comment]
1. The `_async` helper was originally written with the assumption that copying the `arguments` object to an array would be expensive. In the interests of better code size and after noticing that JavaScript engines do a good job with arguments copy, I've opted for a simpler helper that always copies the arguments object to an array.
2. The `inlineHelpers` option generates inline code for `_async`, `_await`, `_awaitIgnored`, `_call` and `_callIgnored` instead of calls to the helper function. Code size is worse for bundles that make heavy use of the helpers, but for smaller bundles or bundles that make a small number of calls it's a win. Latest 0.8.1 has a number of fixes for this option, so be sure to grab that.

**Comment by marvinhagemeister** [comment]
Ohh that's awesome! The option `InlineHelpers` is what I've missed. Thanks again for the quick response 👍 👍
