### ISSUE TITLE
Incorrect transforming break inside switch-case

### ISSUE THREAD

**Issue by Djaler** [rpetrich/babel-plugin-transform-async-to-promises#49]
I create a repo with reproduction: https://github.com/Djaler/babel-plugin-transform-async-to-promises-switch-bug

Brief comparison of the original code with transformed:
```
export async function doSomething() {
    await sleep(1000)
    const errorCode = 2; //why not

    let message = 'Something wrong';

    switch (errorCode) {
        case 2:
            message = "Error 2"
            break
    }

    alert(message)
}
```

```
var doSomething = _async(function () {
  return _await(sleep(1000), function () {
    var errorCode = 2; //why not

    var message = 'Something wrong';

    switch (errorCode) {
      case 2:
        message = "Error 2";
        return;
    }

    alert(message);
  });
});
```

As you can see, `break` turns into `return`, and because of this alert is never called

**Comment by Djaler** [comment]
Additional info: the issue appears in 0.8.15 version

**Comment by agilgur5** [comment]
@rpetrich any word on this? This causes some unexpected and hard to debug issues. We use this inside of TSDX and at least one user downstream is (knowingly) facing this issue https://github.com/jaredpalmer/tsdx/issues/509

I tried to look through the code, but there's a lot of references to switch cases and `replaceReturnsAndBreaks` etc and I've never written a Babel plugin, so I wasn't really able to figure out where the bug is

**Comment by PeterBurner** [comment]
this also happens with `continue` inside of `for`-loops  
its replaced with `return`, which breaks the code logic
